"""initial

Revision ID: 785ab395c24c
Revises: 50047cd4fdaa
Create Date: 2024-11-12 23:39:54.678076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785ab395c24c'
down_revision: Union[str, None] = '50047cd4fdaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
