"""fix column

Revision ID: 8ebad2128e87
Revises: 0f0c4f11ea26
Create Date: 2024-11-13 10:42:25.046635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebad2128e87'
down_revision: Union[str, None] = '0f0c4f11ea26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('users_referer_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['id'])
    op.drop_column('users', 'referer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referer_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_referer_id_fkey', 'users', 'users', ['referer_id'], ['id'])
    op.drop_column('users', 'referrer_id')
    # ### end Alembic commands ###
